name: FTP Connection

on:
  push:
    branches:
      - main

jobs:
  # Job Build : Construire le projet
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          npm run build
          ls

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  # Job Delete : Supprimer les fichiers existants sur le serveur FTP
  delete:
    runs-on: ubuntu-latest
    needs: build  # Le job 'delete' dépend du job 'build'
    steps:
      - name: Delete existing files from FTP server
        run: |
          ftp -n -v jbertrand.fr <<END_SCRIPT
          quote USER hc1opp_juju84350
          quote PASS ${{ secrets.FTP_PASSWORD }}
          binary
          delete index.html
          cd assets
          mdelete *
          mdelete *.png
          cd ..
          bye
          END_SCRIPT

  # Job Copy : Téléverser les nouveaux fichiers sur le serveur FTP
  copy:
    runs-on: ubuntu-latest
    needs: delete
    steps:
      # Télécharger l'artefact dist
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Afficher tous les fichiers téléchargés
        run: |
          echo "Voici les fichiers téléchargés :"
          ls -la

      - name: Extraire l'artefact dist
        run: |
          # Lister tous les fichiers pour vérifier le fichier téléchargé
          files=$(ls)
          echo "Les fichiers téléchargés sont : $files"
          
          # Si un fichier ZIP est trouvé, l'extraire
          for file in $files; do
            if [[ $file == *.zip ]]; then
              unzip "$file" -d dist
              echo "Artefact extrait : $file"
              break
            fi
          done

      # Téléverser le fichier index.html à la racine du serveur FTP
      - name: Upload index.html to the root directory of FTP server
        run: |
          ftp -n -v jbertrand.fr <<END_SCRIPT
          quote USER hc1opp_juju84350
          quote PASS ${{ secrets.FTP_PASSWORD }}
          # Vérifier que le fichier existe avant de le télécharger
          put index.html
          bye
          END_SCRIPT

      - name: Install lftp
        run: sudo apt-get install -y lftp

      # Téléverser les fichiers du dossier assets sur le serveur FTP
      - name: Upload assets folder to the assets directory of FTP server
        run: |
          lftp -u hc1opp_juju84350,${{ secrets.FTP_PASSWORD }} -e "mirror -R assets /assets; bye" jbertrand.fr
