name: FTP Connection

on:
  push:
    branches:
      - main

jobs:
  # Job Build : Construire le projet
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  # Job Delete : Supprimer les fichiers existants sur le serveur FTP
  delete:
    runs-on: ubuntu-latest
    needs: build  # Le job 'delete' dépend du job 'build'
    steps:
      - name: Delete existing files from FTP server
        run: |
          ftp -n -v jbertrand.fr <<END_SCRIPT
          quote USER hc1opp_juju84350
          quote PASS ${{ secrets.FTP_PASSWORD }}
          binary
          delete index.html
          cd assets
          mdelete *
          mdelete *.png
          cd ..
          bye
          END_SCRIPT

  # Job Copy : Téléverser les nouveaux fichiers sur le serveur FTP
  copy:
    runs-on: ubuntu-latest
    needs: delete
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Upload index.html to the root directory of FTP server
        run: |
          ftp -n -v jbertrand.fr <<END_SCRIPT
          quote USER hc1opp_juju84350
          quote PASS ${{ secrets.FTP_PASSWORD }}
          # Téléchargement du fichier index.html à la racine du serveur FTP
          put ./dist/index.html index.html
          bye
          END_SCRIPT
  
      - name: Upload assets folder to the assets directory of FTP server
        run: |
          ftp -n -v jbertrand.fr <<END_SCRIPT
          quote USER hc1opp_juju84350
          quote PASS ${{ secrets.FTP_PASSWORD }}
          # Téléchargement des fichiers du dossier assets dans le dossier assets sur le serveur FTP
          cd assets
          mput ./dist/assets/*
          bye
          END_SCRIPT
